[package]
name = "netpland"
description = "Privileged PE Netplan daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[[bin]]
name = "netpland"
path = "src/main.rs"
doc = false

[dependencies]
clap.workspace = true
ipnet.workspace = true
netplan = { path = "../netplan", version = "0.1.0" }
tokio.workspace = true
uuid.workspace = true

[target.'cfg(windows)'.dependencies]
mimalloc.workspace = true
windows.workspace = true

[target.'cfg(all(windows, target_env = "msvc"))'.dependencies]
vc-ltl.workspace = true

[lints]
workspace = true
