[package]
name = "netplan-ffi"
description = "C ABI for PE Netplan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[lib]
name = "netplan"
crate-type = ["cdylib", "staticlib"]
doc = false

[dependencies]
netplan = { path = "../netplan", version = "0.1.1" }
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
mimalloc.workspace = true

[target.'cfg(all(windows, target_env = "msvc"))'.dependencies]
vc-ltl.workspace = true

[lints]
workspace = true
